name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  Build:
    name: Build
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: "[15.1,15.2,15.6,15.9,16.4,16.9)"

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1

    - name: Restore NuGet packages
      run: nuget restore Sources/MVCMultiLayer.sln

    - name: Build the Solution 
      run: msbuild Sources/MVCMultiLayer.sln /p:Configuration=Release
    
    - name: Execute Unit Tests
      run: vstest.console.exe **/*.Tests.dll
